name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - jupyterlab=3.4.8
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.3.0
  - jinja2=3.1.1
  - pyarrow=8.0.0
  - numpy=1.22.4
  - wandb=0.13.11
  - protobuf=3.20.1
  - jupyterlab_widgets
  - ipywidgets
