name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pytest=6.2.2
  - scipy=1.5.2
  - pip=20.3.3
  - numpy=1.22.4
  - protobuf=3.20.1
  - pip:
      - wandb==0.10.21
# dependencies:
#   - python=3.8.16
#   - pandas=1.2.3
#   - pip=20.3.3
#   - numpy=1.22.4
#   - protobuf=3.20.1
#   - pip:
#     - wandb==0.13.11
