name: components
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.1.1
  - pyyaml=5.3.1
  - hydra-core=1.0.6
  - pip=20.3.3
  - numpy=1.23.0
  - wandb=0.13.11
  - pip:
    - hydra-joblib-launcher==1.1.2
      