name: nyc_airbnb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - mlflow=2.1.1
  - ipython=7.21.0
  - notebook=6.4.0
  - jupyterlab=3.4.8
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - matplotlib=3.7.0
  - pandas=1.5.3
  - git=2.30.2
  - pip=20.3.3
  - wandb=0.13.11
