name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  # - pandas=1.1.4
  # - pip=20.3.3
  # - mlflow=1.14.1
  # - scikit-learn=0.24.1
  # - matplotlib=3.2.2
  # - pillow=8.1.2
  # - pip:
  #     - wandb==0.10.21
  - python=3.8.16
  - pandas=1.5.3    #1.2.3
  - pip=22.3.1      #20.3.3
  - scikit-learn=0.24.1   #0.24.1
  - matplotlib=3.7.0     #3.2.2
  - plotly=5.13.0   #4.4.1
  - pillow=9.4.0    #8.1.2
  - mlflow=2.1.1    #1.14.1
  - wandb=0.13.10
  - pip:
      #- wandb==0.13.10   #0.10.21
      - numpy==1.22.4
      - omegaconf==2.3.0  #2.0.6